import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Clock3, Compass, Heart, MapPin, ShieldCheck, Sparkles, Trees, Users } from "lucide-react";
import { activities, business, images, packages, timeline } from "@/data/site";
import { ActivityCard, CTASection, PackageCard, SectionHeading } from "@/components/ui";
import { VisitorSelector } from "@/components/interactive";

export default function Home() {
  return <main id="main">
    <section className="grain relative flex min-h-screen items-end overflow-hidden bg-forest pb-24 pt-32 text-white">
      <Image src={images.hero} alt="Temporary placeholder for Ban Jungle Adventure hero photography" fill priority sizes="100vw" className="scale-105 object-cover animate-[pulse_14s_ease-in-out_infinite]"/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#071b13]/90 via-[#102b21]/45 to-black/10"/><div className="absolute inset-0 bg-gradient-to-t from-[#071b13]/80 via-transparent to-black/35"/>
      <div className="container-site relative z-10">
        <div className="reveal eyebrow text-gold">Adventure • Nature • Kathmandu</div>
        <h1 className="display mt-6 max-w-5xl reveal">Adventure begins where the <em className="font-normal text-gold">city ends.</em></h1>
        <p className="mt-7 max-w-2xl text-base leading-8 text-white/75 reveal md:text-lg">Discover thrilling outdoor experiences, jungle adventures and peaceful escapes at Ban Jungle Adventure in Kathmandu.</p>
        <div className="mt-9 flex flex-wrap gap-3 reveal"><Link href="#adventures" className="button-primary">Explore adventures <ArrowUpRight size={17}/></Link><Link href="/plan-your-visit" className="button-outline">Plan your visit</Link></div>
        <div className="mt-14 flex flex-col gap-6 border-t border-white/20 pt-7 md:flex-row md:items-center md:justify-between"><a href="#intro" className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.18em] text-white/60">Scroll to explore <ArrowDown size={15}/></a><div className="flex flex-wrap gap-x-7 gap-y-3 rounded-2xl border border-white/15 bg-white/10 px-5 py-4 text-xs backdrop-blur-md"><span className="flex items-center gap-2"><MapPin size={15} className="text-gold"/>Panchmane, Kathmandu</span><span className="flex items-center gap-2"><Clock3 size={15} className="text-gold"/>Hours: confirm before visiting</span><span className="flex items-center gap-2"><Sparkles size={15} className="text-gold"/>Adventure experiences</span></div></div>
      </div>
    </section>

    <section id="intro" className="section-pad bg-cream"><div className="container-site grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><SectionHeading eyebrow="Welcome to the wild" title="A wild escape, just outside Kathmandu." text="Ban Jungle Adventure brings outdoor activity and restorative nature together for families, students, groups and adventure seekers. Come for movement, fresh air, shared experiences and time away from the city rhythm."/><div className="grid grid-cols-2 gap-px overflow-hidden rounded-3xl bg-ink/10">{[[Compass,"Adventure Experiences"],[Heart,"Family Friendly"],[Trees,"Nature Escape"],[Users,"Group Experiences"]].map(([Icon,label]) => { const I=Icon as typeof Compass; return <div key={label as string} className="bg-white p-6"><I className="text-gold"/><div className="mt-8 font-serif text-xl font-bold">{label as string}</div></div>})}</div></div></section>

    <section id="adventures" className="section-pad overflow-hidden bg-white"><div className="container-site"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Featured adventures" title="Choose your adventure." text="Start with the experiences that put Ban Jungle on your map. Requirements, operating status and prices should be confirmed directly before your visit."/><Link href="/attractions" className="button-outline self-start">View all activities <ArrowRight size={16}/></Link></div><div className="mt-14 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{activities.slice(0,6).map((activity,index) => <ActivityCard key={activity.slug} activity={activity} index={index}/>)}</div></div></section>

    <section className="bg-forest py-5 text-white lg:py-0"><div className="grid lg:grid-cols-2"><div className="relative min-h-[520px] overflow-hidden"><Image src={images.zipline} alt="Temporary placeholder for Roller Coaster Zipline" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/><div className="absolute left-6 top-6 rounded-full bg-gold px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-ink">Signature experience</div></div><div className="flex items-center px-6 py-20 lg:px-[10%]"><div><div className="eyebrow text-gold">Roller Coaster Zipline</div><h2 className="section-title mt-6">The ride everyone talks about.</h2><p className="mt-6 max-w-xl leading-8 text-white/65">Follow a twisting route through the forest for a zipline experience that feels different from a straight run. Participation details are confirmed by the team for each guest.</p><div className="mt-8 flex flex-wrap gap-2">{["Height: Contact us","Weight: Contact us","Hours: Contact us","Price: Contact us"].map(i=><span key={i} className="rounded-full border border-white/20 px-4 py-2 text-xs text-white/70">{i}</span>)}</div><Link href="/attractions/roller-coaster-zipline" className="button-primary mt-9">Explore the ride <ArrowUpRight size={16}/></Link></div></div></div></section>

    <section className="section-pad bg-cream"><div className="container-site"><SectionHeading eyebrow="Why Ban Jungle" title="More than an adventure park."/><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] bg-ink/10 md:grid-cols-2 lg:grid-cols-4">{[[Sparkles,"Adventure","Thrilling experiences designed for different types of visitors."],[Trees,"Nature","A forest environment away from the city's busy atmosphere."],[ShieldCheck,"Safety","Clear instructions, equipment guidance and team support."],[Users,"Together","Experiences for families, friends, students and groups."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Trees; return <article key={title as string} className="bg-white p-8"><span className="font-serif text-4xl text-ink/20">0{i+1}</span><I className="mt-12 text-gold" size={30}/><h3 className="mt-5 font-serif text-3xl font-bold">{title as string}</h3><p className="mt-3 text-sm leading-7 text-ink/60">{text as string}</p></article>})}</div></div></section>

    <section className="section-pad bg-[#0b251b] text-white"><div className="container-site"><SectionHeading light eyebrow="Find your pace" title="A different jungle for every visitor." text="Choose who you are visiting with to see the types of experiences that may fit your day."/><VisitorSelector/></div></section>

    <section className="relative min-h-[760px] overflow-hidden py-24 text-white"><Image src={images.stay} alt="Temporary placeholder for Ban Jungle safari tent night stay" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/45 to-transparent"/><div className="container-site relative z-10 flex min-h-[570px] items-center"><div className="max-w-2xl"><div className="eyebrow text-gold">Night stay</div><h2 className="section-title mt-6">Stay where the forest gets quiet.</h2><p className="mt-6 leading-8 text-white/70">Slow the day down with a safari tent stay, meals and the atmosphere of the forest after the activities end. Confirm accommodation, dinner, breakfast and package inclusions directly with the team.</p><div className="mt-8 flex flex-wrap gap-2">{["Safari tent","Dinner & breakfast — confirm","Nature experience","Adventure + stay inquiry"].map(i=><span key={i} className="rounded-full bg-white/10 px-4 py-2 text-xs backdrop-blur">{i}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link href="/stay" className="button-primary">Explore night stay</Link><a href={business.whatsapp} className="button-outline">Book on WhatsApp</a></div></div></div></section>

    <section className="section-pad bg-cream"><div className="container-site"><SectionHeading eyebrow="Packages" title="Build the day around your people." text="Choose a starting point, then contact the team for current inclusions, availability and pricing."/><div className="mt-14 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{packages.slice(0,3).map(item=><PackageCard key={item.slug} item={item}/>)}</div><div className="mt-14 text-center"><Link href="/packages" className="button-outline">Discover all packages <ArrowRight size={16}/></Link></div></div></section>

    <section className="bg-white"><div className="grid lg:grid-cols-2"><div className="flex items-center px-6 py-24 lg:px-[10%]"><div><div className="eyebrow text-jungle">Dining</div><h2 className="section-title mt-6">Refuel in the jungle.</h2><p className="mt-6 max-w-xl leading-8 text-ink/65">Make food part of the experience. The restaurant welcomes adventure days, family time and group dining in a relaxed natural setting. Contact the team for current menus and dietary options.</p><Link href="/dining" className="button-primary mt-9">Explore dining <ArrowUpRight size={16}/></Link></div></div><div className="relative min-h-[570px]"><Image src={images.dining} alt="Temporary placeholder for Ban Jungle restaurant and food" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/></div></div></section>

    <section className="section-pad bg-cream"><div className="container-site grid gap-16 lg:grid-cols-[.75fr_1.25fr]"><div className="lg:sticky lg:top-32 lg:self-start"><SectionHeading eyebrow="Our story" title="A place grown with purpose." text="The following timeline presents business-provided history and should be verified with the Ban Jungle team before publication."/><Link href="/about-us" className="button-primary mt-8">Discover our story</Link></div><div className="border-l border-ink/20 pl-8">{timeline.map(item=><article key={item.year} className="relative border-b border-ink/15 py-9 first:pt-0"><span className="absolute -left-[2.55rem] top-10 size-4 rounded-full border-4 border-cream bg-gold first:top-1"/><div className="text-xs font-extrabold uppercase tracking-[.17em] text-jungle">{item.year}</div><h3 className="mt-3 font-serif text-3xl font-bold">{item.title}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-ink/60">{item.text}</p></article>)}</div></div></section>
    <CTASection/>
  </main>;
}
