import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Compass, Footprints, Play, ShieldCheck, Sparkles, Trees, Users } from "lucide-react";
import { activities, business, images, packages, timeline } from "@/data/site";
import { ActivityCard, PackageCard, SectionHeading } from "@/components/ui";
import { AdventureJourney, FAQAccordion, VisitorSelector } from "@/components/interactive";

const principles = [
  [Sparkles, "Adventure", "Thrilling experiences for visitors who want to move beyond the ordinary."],
  [Trees, "Nature", "A forest setting where fresh air and open space change the pace of the day."],
  [ShieldCheck, "Safety", "Activity instructions, participation guidance and support from the on-site team."],
  [Users, "Together", "Shared experiences for families, friends, schools and organised groups."],
] as const;

export default function Home() {
  return <main id="main">
    <section className="hero-jungle grain relative min-h-[980px] bg-forest pt-36 text-white lg:min-h-[900px] lg:pt-48">
      <div className="absolute inset-0 overflow-hidden"><Image src={images.zipline} alt="Temporary zipline hero placeholder for Ban Jungle Adventure" fill priority sizes="100vw" className="hero-jungle-image object-cover"/></div>
      <div className="absolute inset-0 bg-gradient-to-r from-[#03140b]/95 via-[#092417]/55 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-[#061b10]/75 via-transparent to-black/30"/>
      <div className="container-site relative z-10 pt-16 lg:pt-20">
        <p className="hero-script reveal">Discover <span aria-hidden="true">◇</span></p>
        <h1 className="mt-1 max-w-4xl text-[clamp(3rem,7vw,6.4rem)] font-extrabold leading-[.92] tracking-[-.055em] text-[#b8ef35] reveal">Ban Jungle Adventure.</h1>
        <p className="mt-6 max-w-xl text-base leading-7 text-white/75 reveal">Thrilling outdoor experiences, peaceful jungle escapes and shared adventures in Panchmane, Kathmandu.</p>
        <div className="mt-8 flex flex-wrap gap-4 reveal"><Link href="#adventures" className="hero-button"> <Compass size={19}/>Explore activities <ArrowRight size={18}/></Link><a href="#story" className="hero-button-outline"><Play size={18} fill="currentColor"/>Watch our story</a></div>
      </div>
      <div className="hero-organic-edge" aria-hidden="true"/>
      <div className="container-site relative z-20 mt-16 grid gap-5 px-4 md:absolute md:inset-x-0 md:bottom-[-116px] md:grid-cols-3 md:px-0">
        <HeroCard href="/attractions/roller-coaster-zipline" image={images.zipline} title="Zipline Adventure" icon={Compass} eager/>
        <HeroCard href="/plan-your-visit" image={images.nature} title="Jungle Escape" icon={Footprints}/>
        <HeroCard href="/packages/family-adventure" image={images.group} title="Family Fun" icon={Users}/>
      </div>
    </section>
    <div className="h-8 bg-cream md:h-44" aria-hidden="true"/>

    <section id="intro" className="section-pad overflow-hidden bg-cream"><div className="container-site grid gap-16 lg:grid-cols-[.92fr_1.08fr] lg:items-center">
      <div className="relative min-h-[580px]" data-reveal="left"><div className="clip-image absolute inset-y-0 left-0 w-[82%]" data-reveal><Image src={images.nature} alt="Temporary forest placeholder for Ban Jungle Adventure" fill sizes="(max-width:1024px) 85vw,42vw" className="object-cover"/></div><div className="float-slow absolute bottom-4 right-0 h-64 w-[48%] overflow-hidden rounded-[1.5rem] border-[10px] border-cream"><Image src={images.group} alt="Temporary group experience placeholder" fill sizes="25vw" className="object-cover"/></div><div className="absolute right-0 top-8 grid size-32 place-items-center rounded-full bg-gold p-4 text-center text-[10px] font-extrabold uppercase leading-5 tracking-[.12em] text-ink">Adventure<br/>meets<br/>nature</div></div>
      <div data-reveal="right"><SectionHeading eyebrow="About Ban Jungle" title="A wild escape, made for people who want more from a day outside." text="Ban Jungle Adventure brings active outdoor experiences, a restorative forest atmosphere, dining and night stays together in Panchmane. It is a place to reconnect with nature and each other without leaving Kathmandu behind."/><div className="mt-9 grid gap-5 sm:grid-cols-2"><div className="border-t border-ink/20 pt-5"><h3 className="font-serif text-2xl font-bold">Designed for nature lovers</h3><p className="mt-2 text-sm leading-6 text-ink/55">Fresh air, forest surroundings and room to slow down.</p></div><div className="border-t border-ink/20 pt-5"><h3 className="font-serif text-2xl font-bold">Adventure at your pace</h3><p className="mt-2 text-sm leading-6 text-ink/55">Discover activities for different visitor groups and comfort levels.</p></div></div><Link href="/about-us" className="button-primary mt-9">More about us <ArrowUpRight size={16}/></Link></div>
    </div></section>

    <section id="adventures" className="section-pad overflow-hidden bg-white"><div className="container-site flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between" data-reveal><SectionHeading eyebrow="Featured adventures" title="From first step to full thrill, find your way into the wild." text="Explore the experiences that define a Ban Jungle day. Current requirements, operating status and prices should be confirmed before visiting."/><Link href="/attractions" className="button-outline self-start">View every activity <ArrowRight size={16}/></Link></div><div className="horizontal-cards mt-12">{activities.map((activity,index)=><div key={activity.slug} data-reveal style={{transitionDelay:`${index*70}ms`}}><ActivityCard activity={activity}/></div>)}</div></section>

    <div className="overflow-hidden border-y border-ink/10 bg-gold py-5" aria-hidden="true"><div className="marquee-track">{[...Array(2)].flatMap((_,set)=>["Outdoor adventure","Jungle escape","Family time","Roller Coaster Zipline","Night stay","Kathmandu nature"].map((item,i)=><span key={`${set}-${i}`} className="flex items-center gap-8 pr-8 font-serif text-3xl font-bold"><Sparkles size={20}/>{item}</span>))}</div></div>

    <section className="section-pad bg-cream"><div className="container-site grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div data-reveal="left"><SectionHeading eyebrow="Why choose us" title="More than an adventure park." text="Come for the adrenaline. Stay for the feeling of being together in a place shaped by the outdoors."/><Link href="/plan-your-visit" className="button-primary mt-8">Plan the day <ArrowUpRight size={16}/></Link></div><div className="relative min-h-[600px]" data-reveal="right"><Image src={images.climbing} alt="Temporary Ban Jungle activity placeholder" fill sizes="(max-width:1024px) 100vw,55vw" className="rounded-[2rem] object-cover"/><div className="absolute inset-x-4 bottom-4 grid overflow-hidden rounded-2xl bg-[#0b251b]/95 text-white backdrop-blur md:grid-cols-2">{principles.map(([Icon,title,text])=><article key={title} className="group border-b border-white/10 p-5 last:border-0 md:border-r"><Icon className="text-gold transition-transform group-hover:rotate-12" size={22}/><h3 className="mt-4 font-serif text-2xl font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-white/55">{text}</p></article>)}</div></div></div></section>

    <section className="bg-forest text-white"><div className="grid lg:grid-cols-2"><div className="clip-image relative min-h-[620px]" data-reveal><Image src={images.zipline} alt="Temporary placeholder for Roller Coaster Zipline" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/><div className="absolute left-6 top-6 rounded-full bg-gold px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-ink">Signature experience</div></div><div className="flex items-center px-6 py-20 lg:px-[10%]" data-reveal="right"><div><div className="eyebrow text-gold">Roller Coaster Zipline</div><h2 className="section-title mt-6">The ride everyone talks about.</h2><p className="mt-6 max-w-xl leading-8 text-white/65">Follow a twisting route through the forest for a zipline experience that feels different from a straight run. Participation details are confirmed by the team for each guest.</p><div className="mt-8 flex flex-wrap gap-2">{["Height: Contact us","Weight: Contact us","Hours: Contact us","Price: Contact us"].map(i=><span key={i} className="rounded-full border border-white/20 px-4 py-2 text-xs text-white/70">{i}</span>)}</div><Link href="/attractions/roller-coaster-zipline" className="button-primary mt-9">Explore the ride <ArrowUpRight size={16}/></Link></div></div></div></section>

    <section className="section-pad bg-[#071b13] text-white"><div className="container-site"><div data-reveal><SectionHeading light eyebrow="Explore adventures" title="Hover a path. See where it leads." text="Move through Ban Jungle's experiences and choose the one that feels like your next story."/></div><div className="mt-14" data-reveal><AdventureJourney/></div></div></section>

    <section className="section-pad bg-white"><div className="container-site"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between" data-reveal><SectionHeading eyebrow="Our gallery" title="The wild looks good on everyone." text="A preview layout ready for real Ban Jungle Adventure photography. Current imagery is temporary and clearly identified in its alt text."/><Link href="/gallery" className="button-outline self-start">Open gallery <ArrowRight size={16}/></Link></div><div className="mt-12 grid gap-4 md:grid-cols-12"><GalleryImage src={images.zipline} className="md:col-span-7 md:row-span-2" label="Adventure"/><GalleryImage src={images.stay} className="md:col-span-5" label="Stay"/><GalleryImage src={images.dining} className="md:col-span-5" label="Dining"/></div></div></section>

    <section id="story" className="grain relative min-h-[760px] overflow-hidden py-24 text-white"><Image src={images.nature} alt="Temporary cinematic forest story placeholder" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-black/55"/><div className="container-site relative z-10 flex min-h-[570px] flex-col items-center justify-center text-center" data-reveal="scale"><button aria-label="Play Ban Jungle story video placeholder" className="grid size-24 place-items-center rounded-full border border-white/50 bg-white/10 backdrop-blur transition-colors hover:bg-gold hover:text-ink"><Play fill="currentColor"/></button><div className="eyebrow mt-10 text-gold">Our story</div><h2 className="section-title mt-6 max-w-5xl">A journey built on adventure and the desire to bring people closer to the outdoors.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/65">Video-ready storytelling area. Business-owned footage can replace this temporary image without changing the layout.</p></div></section>

    <section className="section-pad bg-cream"><div className="container-site" data-reveal><SectionHeading eyebrow="Find your pace" title="A different jungle for every visitor." text="Choose who you are visiting with to see the types of experiences that may fit your day."/><div className="mt-2 rounded-[2rem] bg-forest p-5 md:p-10"><VisitorSelector/></div></div></section>

    <section className="relative min-h-[760px] overflow-hidden py-24 text-white"><Image src={images.stay} alt="Temporary placeholder for Ban Jungle safari tent night stay" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/45 to-transparent"/><div className="container-site relative z-10 flex min-h-[570px] items-center"><div className="max-w-2xl" data-reveal="left"><div className="eyebrow text-gold">Night stay</div><h2 className="section-title mt-6">Stay where the forest gets quiet.</h2><p className="mt-6 leading-8 text-white/70">Slow the day down with a safari tent stay, meals and the atmosphere of the forest after the activities end. Confirm accommodation, dinner, breakfast and package inclusions directly with the team.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/stay" className="button-primary">Explore night stay</Link><a href={business.whatsapp} className="button-outline">Book on WhatsApp</a></div></div></div></section>

    <section className="section-pad bg-cream"><div className="container-site"><div data-reveal><SectionHeading eyebrow="Packages" title="Build the day around your people." text="Choose a starting point, then contact the team for current inclusions, availability and pricing."/></div><div className="mt-14 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{packages.slice(0,3).map((item,i)=><div key={item.slug} data-reveal style={{transitionDelay:`${i*90}ms`}}><PackageCard item={item}/></div>)}</div></div></section>

    <section className="bg-white"><div className="grid lg:grid-cols-2"><div className="flex items-center px-6 py-24 lg:px-[10%]" data-reveal="left"><div><div className="eyebrow text-jungle">Dining</div><h2 className="section-title mt-6">Refuel in the jungle.</h2><p className="mt-6 max-w-xl leading-8 text-ink/65">Make food part of the experience. The restaurant welcomes adventure days, family time and group dining in a relaxed natural setting. Contact the team for current menus and dietary options.</p><Link href="/dining" className="button-primary mt-9">Explore dining <ArrowUpRight size={16}/></Link></div></div><div className="clip-image relative min-h-[570px]" data-reveal><Image src={images.dining} alt="Temporary placeholder for Ban Jungle restaurant and food" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/></div></div></section>

    <section className="section-pad bg-cream"><div className="container-site grid gap-16 lg:grid-cols-[.75fr_1.25fr]"><div className="lg:sticky lg:top-32 lg:self-start" data-reveal="left"><SectionHeading eyebrow="Our story" title="A place grown with purpose." text="The following timeline presents business-provided history and should be verified with the Ban Jungle team before publication."/><Link href="/about-us" className="button-primary mt-8">Discover our story</Link></div><div className="border-l border-ink/20 pl-8">{timeline.map((item,i)=><article key={item.year} className="relative border-b border-ink/15 py-9 first:pt-0" data-reveal style={{transitionDelay:`${i*70}ms`}}><span className="absolute -left-[2.55rem] top-10 size-4 rounded-full border-4 border-cream bg-gold first:top-1"/><div className="text-xs font-extrabold uppercase tracking-[.17em] text-jungle">{item.year}</div><h3 className="mt-3 font-serif text-3xl font-bold">{item.title}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-ink/60">{item.text}</p></article>)}</div></div></section>

    <section className="section-pad bg-white"><div className="container-site grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div data-reveal="left"><SectionHeading eyebrow="Frequently asked" title="Good questions before a great day." text="Operational details can change, so the team should confirm current prices, requirements, hours and availability."/><div className="relative mt-8 h-64 overflow-hidden rounded-[2rem]"><Image src={images.kids} alt="Temporary family adventure FAQ placeholder" fill sizes="40vw" className="object-cover"/></div></div><div data-reveal="right"><FAQAccordion limit={5}/><Link href="/faq" className="button-outline mt-8">See all questions <ArrowRight size={16}/></Link></div></div></section>

    <section className="bg-gold py-14 text-ink"><div className="container-site flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between" data-reveal><div><div className="text-xs font-bold uppercase tracking-[.2em]">Your forest escape starts here</div><h2 className="mt-2 font-serif text-4xl font-bold lg:text-5xl">Ready for a different kind of day?</h2></div><div className="flex flex-wrap gap-3"><Link href="/contact#booking" className="button-light">Book your adventure <ArrowUpRight size={17}/></Link><a href={business.whatsapp} target="_blank" rel="noreferrer" className="button-outline">WhatsApp us</a></div></div></section>
  </main>;
}

function GalleryImage({src,className,label}:{src:string;className:string;label:string}) {
  return <Link href="/gallery" className={`image-card group relative min-h-[320px] overflow-hidden rounded-[2rem] ${className}`} data-reveal><Image src={src} alt={`Temporary ${label.toLowerCase()} gallery placeholder`} fill sizes="(max-width:768px) 100vw,60vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><div className="absolute inset-x-0 bottom-0 flex items-center justify-between p-6 text-white"><strong className="font-serif text-3xl">{label}</strong><span className="card-arrow grid size-12 place-items-center rounded-full bg-gold text-ink"><ArrowUpRight/></span></div></Link>;
}

function HeroCard({href,image,title,icon:Icon,eager=false}:{href:string;image:string;title:string;icon:typeof Compass;eager?:boolean}) {
  return <Link href={href} className="hero-card group" aria-label={`Explore ${title}`}><div className="relative h-40 overflow-hidden"><Image src={image} alt={`Temporary ${title} hero card placeholder`} fill loading={eager?"eager":"lazy"} sizes="(max-width:768px) 100vw,33vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/><span className="absolute bottom-4 left-5 grid size-14 place-items-center rounded-full border-2 border-[#b8ef35] bg-[#102b21]/70 text-[#b8ef35] backdrop-blur"><Icon size={25}/></span><span className="card-arrow absolute bottom-4 right-4 grid size-12 place-items-center rounded-full bg-white text-ink shadow-lg"><ArrowRight/></span></div><div className="flex min-h-20 items-center px-6"><strong className="text-xl font-extrabold text-[#102b21] md:text-2xl">{title}</strong></div></Link>;
}
