import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Breadcrumbs, CTASection, InfoList } from "@/components/ui";
import { packages } from "@/data/site";
export function generateStaticParams(){return packages.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=packages.find(x=>x.slug===slug);return {title:p?.name??"Package",description:p?.description}}
export default async function PackageDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=packages.find(x=>x.slug===slug);if(!p)notFound();return <main id="main" className="pt-24"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Packages",href:"/packages"},{label:p.name}]}/><section className="container-site grid overflow-hidden rounded-[2rem] bg-forest text-white lg:grid-cols-2"><div className="relative min-h-[520px]"><Image src={p.image} alt={`Temporary placeholder for ${p.name}`} fill priority sizes="50vw" className="object-cover"/></div><div className="p-8 md:p-14"><div className="eyebrow text-gold">{p.audience}</div><h1 className="display mt-6">{p.name}</h1><p className="mt-6 leading-8 text-white/65">{p.description}</p><div className="mt-8 rounded-2xl border border-white/15 p-6"><span className="text-xs font-bold uppercase tracking-wider text-gold">Pricing</span><p className="mt-2 font-serif text-3xl font-bold">Contact us for pricing</p></div></div></section><section className="section-pad bg-cream"><div className="container-site grid gap-8 md:grid-cols-2"><PackageBlock title="Who it's for" items={[p.audience,"Visitors looking for a flexible outdoor experience"]}/><PackageBlock title="What's included" items={["Inclusions are confirmed by the team","Activities depend on availability","Food or stay details must be confirmed"]}/><PackageBlock title="Schedule" items={["Contact us to discuss your preferred date","Confirm arrival time before travelling"]}/><PackageBlock title="Important information" items={["Participation requirements vary","Weather may affect outdoor activities","An inquiry is not a confirmed booking"]}/></div></section><CTASection/></main>}
function PackageBlock({title,items}:{title:string;items:string[]}){return <article className="rounded-[2rem] bg-white p-8"><h2 className="font-serif text-3xl font-bold">{title}</h2><div className="mt-6"><InfoList items={items}/></div></article>}
